package com.safecode.entity;

import jakarta.persistence.*;

/**
 * JPA entity that persists a single security finding linked to an {@link AuditEntity}.
 * Fields mirror the {@link com.safecode.model.Finding} POJO.
 */
@Entity
@Table(name = "findings")
public class FindingEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Original AUDIT-NNN identifier generated by the scanner. */
    @Column(name = "finding_ref", nullable = false, length = 32)
    private String findingRef;

    @Column(nullable = false, length = 64)
    private String category;

    @Column(nullable = false, length = 32)
    private String severity;

    @Column(nullable = false, length = 1024)
    private String file;

    @Column(nullable = false)
    private int line;

    @Column(nullable = false, length = 512)
    private String issue;

    @Column(nullable = false, length = 256)
    private String evidence;

    @Column(nullable = false, length = 1024)
    private String fix;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "audit_id", nullable = false)
    private AuditEntity audit;

    public FindingEntity() {}

    public FindingEntity(String findingRef, String category, String severity,
                         String file, int line,
                         String issue, String evidence, String fix,
                         AuditEntity audit) {
        this.findingRef = findingRef;
        this.category   = category;
        this.severity   = severity;
        this.file       = file;
        this.line       = line;
        this.issue      = issue;
        this.evidence   = evidence;
        this.fix        = fix;
        this.audit      = audit;
    }

    // ---- Getters & Setters ----

    public Long getId()                              { return id; }

    public String getFindingRef()                    { return findingRef; }
    public void   setFindingRef(String findingRef)   { this.findingRef = findingRef; }

    public String getCategory()                      { return category; }
    public void   setCategory(String category)       { this.category = category; }

    public String getSeverity()                      { return severity; }
    public void   setSeverity(String severity)       { this.severity = severity; }

    public String getFile()                          { return file; }
    public void   setFile(String file)               { this.file = file; }

    public int getLine()                             { return line; }
    public void setLine(int line)                    { this.line = line; }

    public String getIssue()                         { return issue; }
    public void   setIssue(String issue)             { this.issue = issue; }

    public String getEvidence()                      { return evidence; }
    public void   setEvidence(String evidence)       { this.evidence = evidence; }

    public String getFix()                           { return fix; }
    public void   setFix(String fix)                 { this.fix = fix; }

    public AuditEntity getAudit()                    { return audit; }
    public void        setAudit(AuditEntity audit)   { this.audit = audit; }
}
